/**
 * Data-loading helpers for the Next.js app.
 *
 * These functions read from content/processed/ which is generated by the
 * preprocessing pipeline (scripts/build.ts) before every build.
 * All reads are synchronous — this is fine for static generation.
 */

import fs from 'fs'
import path from 'path'
import { AlignedParagraphGroup, ChapterMeta } from './types'

const PROCESSED_DIR  = path.join(process.cwd(), 'content', 'processed')
const CONTENT_DIR    = path.join(process.cwd(), 'content')

export interface ChapterStructureRow {
  slug: string
  label1818: string | null
  label1831: string | null
  /** Volume group header to render before this row in the 1818 column (e.g. "Volume II") */
  volBreak?: string
}

export interface ChapterStructure {
  rows: ChapterStructureRow[]
}

export function readChapterList(): ChapterMeta[] {
  const file = path.join(PROCESSED_DIR, 'chapters.json')
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as ChapterMeta[]
}

export function readChapter(slug: string): AlignedParagraphGroup[] {
  const file = path.join(PROCESSED_DIR, `ch${slug}.json`)
  if (!fs.existsSync(file)) return []
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as AlignedParagraphGroup[]
}

export function readChapterMeta(slug: string): ChapterMeta | undefined {
  const chapters = readChapterList()
  return chapters.find((c) => c.slug === slug)
}

export function readChapterStructure(): ChapterStructure {
  const file = path.join(CONTENT_DIR, 'chapter-structure.json')
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as ChapterStructure
}

/** Adjacent chapter slugs for prev/next navigation. */
export function getAdjacentChapters(
  slug: string,
): { prev: ChapterMeta | null; next: ChapterMeta | null } {
  const chapters = readChapterList()
  const idx = chapters.findIndex((c) => c.slug === slug)
  return {
    prev: idx > 0 ? chapters[idx - 1] : null,
    next: idx < chapters.length - 1 ? chapters[idx + 1] : null,
  }
}
