/**
 * Data-loading helpers for the Next.js app.
 *
 * These functions read from content/processed/ which is generated by the
 * preprocessing pipeline (scripts/build.ts) before every build.
 * All reads are synchronous — this is fine for static generation.
 */

import fs from 'fs'
import path from 'path'
import { AlignedParagraphGroup, ChapterMeta } from './types'

const PROCESSED_DIR  = path.join(process.cwd(), 'content', 'processed')
const CONTENT_DIR    = path.join(process.cwd(), 'content')

export interface ChapterStructureRow {
  slug: string
  label1818: string | null
  label1831: string | null
  /** Volume group header to render before this row in the 1818 column (e.g. "Volume II") */
  volBreak?: string
  /** Explains when a 1831 chapter was created by splitting an 1818 chapter (label1818 will be null). */
  splitNote?: string
}

export interface ChapterStructure {
  rows: ChapterStructureRow[]
}

export function readChapterList(): ChapterMeta[] {
  const file = path.join(PROCESSED_DIR, 'chapters.json')
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as ChapterMeta[]
}

export function readChapter(slug: string): AlignedParagraphGroup[] {
  const file = path.join(PROCESSED_DIR, `ch${slug}.json`)
  if (!fs.existsSync(file)) return []
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as AlignedParagraphGroup[]
}

export function readChapterMeta(slug: string): ChapterMeta | undefined {
  const chapters = readChapterList()
  return chapters.find((c) => c.slug === slug)
}

export function readChapterStructure(): ChapterStructure {
  const file = path.join(CONTENT_DIR, 'chapter-structure.json')
  const raw = fs.readFileSync(file, 'utf-8')
  return JSON.parse(raw) as ChapterStructure
}

/**
 * Returns the plain text of the first body paragraph for a chapter,
 * truncated to `maxLen` characters (with an ellipsis if trimmed).
 * Falls back across editions in the order supplied.
 */
export function getChapterFirstParagraph(
  slug: string,
  preferEditions: string[] = ['1831', '1818'],
  maxLen = 200,
): string | undefined {
  const groups = readChapter(slug)
  for (const edition of preferEditions) {
    for (const group of groups) {
      const para = group.paragraphs[edition as '1818' | '1831']
      if (para && para.elementType === 'body' && para.text.trim()) {
        const text = para.text.trim()
        return text.length > maxLen ? text.slice(0, maxLen).trimEnd() + '…' : text
      }
    }
  }
  return undefined
}

/**
 * Adjacent chapters for prev/next navigation.
 * When `edition` is supplied, chapters not available in that edition are
 * skipped so the nav never points to a chapter the reader can't view.
 */
export function getAdjacentChapters(
  slug: string,
  edition?: string,
): { prev: ChapterMeta | null; next: ChapterMeta | null } {
  const chapters = readChapterList()
  const idx = chapters.findIndex((c) => c.slug === slug)

  const inEdition = (c: ChapterMeta) =>
    !edition || (c.editions as string[]).includes(edition)

  let prev: ChapterMeta | null = null
  for (let i = idx - 1; i >= 0; i--) {
    if (inEdition(chapters[i])) { prev = chapters[i]; break }
  }

  let next: ChapterMeta | null = null
  for (let i = idx + 1; i < chapters.length; i++) {
    if (inEdition(chapters[i])) { next = chapters[i]; break }
  }

  return { prev, next }
}
